In [83]:
import numpy as np

In [84]:
np

<module 'numpy' from '/opt/anaconda2/lib/python2.7/site-packages/numpy/__init__.pyc'>

In [11]:
lst = [[1,2,3], [1,2,3], [1,2,3]]

In [12]:
type(lst)

list

In [85]:
arr = np.array(lst)

In [86]:
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [21]:
board = [[1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1]]

In [87]:
arr = np.array(board)

In [88]:
board = np.ones((8,8), dtype = int)
boolen = np.zeros((8,8), dtype = bool)

In [89]:
board

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
board = board * 13

In [90]:
np.array(board, dtype = bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [91]:
np.random.random((5,5))

array([[0.49488243, 0.17667161, 0.22783551, 0.56416795, 0.78643901],
       [0.37575759, 0.97070215, 0.69584456, 0.88648763, 0.93936651],
       [0.50766796, 0.07092935, 0.12412812, 0.85432982, 0.84834643],
       [0.46262942, 0.54066045, 0.65301278, 0.13593491, 0.11011315],
       [0.81171866, 0.41094118, 0.45830094, 0.14982636, 0.86505939]])

In [92]:
np.random.randint(0, 5, (5,5))

array([[0, 0, 4, 3, 0],
       [4, 2, 0, 1, 4],
       [2, 1, 2, 2, 0],
       [1, 2, 0, 0, 2],
       [4, 2, 0, 3, 0]])

In [93]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])